import {
  Activity,
  Bot,
  CircleHelp,
  History,
  LayoutDashboard,
  ShieldCheck,
  WalletCards,
} from "lucide-react";
import type { AgentRule, AlertItem, MarketModel, NavItem, Transaction } from "./types";

export const navItems: NavItem[] = [
  { id: "overview", label: "总览", icon: LayoutDashboard, active: true },
  { id: "market", label: "模型市场", icon: Activity },
  { id: "agent", label: "平台智能体", icon: Bot },
  { id: "wallet", label: "钱包", icon: WalletCards },
  { id: "risk", label: "风控", icon: ShieldCheck },
  { id: "history", label: "流水", icon: History },
  { id: "guide", label: "帮助", icon: CircleHelp },
];

export const marketModels: MarketModel[] = [
  {
    id: "gpt-5-5",
    name: "GPT-5.5",
    provider: "OpenAI",
    inputPriceUsd: 5,
    outputPriceUsd: 30,
    cachedInputPriceUsd: 0.5,
    unit: "1M input tokens",
    inventory: 4800000,
    change24h: -0.2,
    risk: "High",
    accent: "bg-indigo-500",
    source: "OpenAI API pricing",
  },
  {
    id: "gpt-5-4",
    name: "GPT-5.4",
    provider: "OpenAI",
    inputPriceUsd: 2.5,
    outputPriceUsd: 15,
    cachedInputPriceUsd: 0.25,
    unit: "1M input tokens",
    inventory: 7200000,
    change24h: 0,
    risk: "Watch",
    accent: "bg-blue-500",
    source: "OpenAI API pricing",
  },
  {
    id: "gpt-5-4-mini",
    name: "GPT-5.4 mini",
    provider: "OpenAI",
    inputPriceUsd: 0.75,
    outputPriceUsd: 4.5,
    cachedInputPriceUsd: 0.075,
    unit: "1M input tokens",
    inventory: 12000000,
    change24h: -0.1,
    risk: "Low",
    accent: "bg-sky-500",
    source: "OpenAI API pricing",
  },
  {
    id: "gpt-5-4-nano",
    name: "GPT-5.4 nano",
    provider: "OpenAI",
    inputPriceUsd: 0.2,
    outputPriceUsd: 1.25,
    cachedInputPriceUsd: 0.02,
    unit: "1M input tokens",
    inventory: 42000000,
    change24h: 0.1,
    risk: "Low",
    accent: "bg-cyan-500",
    source: "OpenAI API pricing",
  },
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "DeepSeek",
    inputPriceUsd: 0.435,
    outputPriceUsd: 0.87,
    cachedInputPriceUsd: 0.003625,
    unit: "1M input tokens",
    inventory: 25000000,
    change24h: 0.1,
    risk: "Watch",
    accent: "bg-emerald-500",
    source: "DeepSeek API pricing",
  },
  {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    provider: "DeepSeek",
    inputPriceUsd: 0.14,
    outputPriceUsd: 0.28,
    cachedInputPriceUsd: 0.0028,
    unit: "1M input tokens",
    inventory: 64000000,
    change24h: 0,
    risk: "Low",
    accent: "bg-lime-500",
    source: "DeepSeek API pricing",
  },
  {
    id: "claude-sonnet",
    name: "Claude Sonnet 4.6",
    provider: "Anthropic",
    inputPriceUsd: 3,
    outputPriceUsd: 15,
    cachedInputPriceUsd: 0.3,
    unit: "1M input tokens",
    inventory: 8000000,
    change24h: -0.4,
    risk: "Low",
    accent: "bg-violet-500",
    source: "Anthropic pricing",
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    provider: "Anthropic",
    inputPriceUsd: 1,
    outputPriceUsd: 5,
    cachedInputPriceUsd: 0.1,
    unit: "1M input tokens",
    inventory: 14000000,
    change24h: -0.1,
    risk: "Low",
    accent: "bg-fuchsia-500",
    source: "Anthropic pricing",
  },
  {
    id: "gemini-3-5-flash",
    name: "Gemini 3.5 Flash",
    provider: "Google",
    inputPriceUsd: 1.5,
    outputPriceUsd: 9,
    cachedInputPriceUsd: 0.15,
    unit: "1M input tokens",
    inventory: 11000000,
    change24h: 0,
    risk: "Watch",
    accent: "bg-rose-500",
    source: "Google Gemini pricing",
  },
  {
    id: "gemini-3-1-pro-preview",
    name: "Gemini 3.1 Pro Preview",
    provider: "Google",
    inputPriceUsd: 0.5,
    outputPriceUsd: 3,
    cachedInputPriceUsd: 0.05,
    unit: "1M input tokens",
    inventory: 9000000,
    change24h: 0.2,
    risk: "Watch",
    accent: "bg-pink-500",
    source: "Google Gemini pricing",
  },
  {
    id: "gemini-3-1-flash-lite",
    name: "Gemini 3.1 Flash-Lite",
    provider: "Google",
    inputPriceUsd: 0.25,
    outputPriceUsd: 1.5,
    cachedInputPriceUsd: 0.025,
    unit: "1M input tokens",
    inventory: 52000000,
    change24h: -0.1,
    risk: "Low",
    accent: "bg-yellow-500",
    source: "Google Gemini pricing",
  },
  {
    id: "mistral-large-3",
    name: "Mistral Large 3",
    provider: "Mistral AI",
    inputPriceUsd: 0.5,
    outputPriceUsd: 1.5,
    unit: "1M input tokens",
    inventory: 16000000,
    change24h: 0,
    risk: "Low",
    accent: "bg-orange-500",
    source: "Mistral AI pricing",
  },
  {
    id: "mistral-small-4",
    name: "Mistral Small 4",
    provider: "Mistral AI",
    inputPriceUsd: 0.1,
    outputPriceUsd: 0.3,
    unit: "1M input tokens",
    inventory: 58000000,
    change24h: 0.1,
    risk: "Low",
    accent: "bg-red-500",
    source: "Mistral AI pricing",
  },
  {
    id: "devstral-small-2",
    name: "Devstral Small 2",
    provider: "Mistral AI",
    inputPriceUsd: 0.1,
    outputPriceUsd: 0.3,
    unit: "1M input tokens",
    inventory: 28000000,
    change24h: -0.2,
    risk: "Watch",
    accent: "bg-stone-500",
    source: "Mistral AI pricing",
  },
];

export const priceSeries = [
  { time: "09:00", gpt55: 5, gpt: 0.75, deepseek: 0.435, claude: 3, gemini: 1.5, walletLimit: 842.2 },
  { time: "10:00", gpt55: 5, gpt: 0.75, deepseek: 0.435, claude: 3, gemini: 1.5, walletLimit: 841.6 },
  { time: "11:00", gpt55: 5, gpt: 0.75, deepseek: 0.435, claude: 3, gemini: 1.5, walletLimit: 839.9 },
  { time: "12:00", gpt55: 5, gpt: 0.75, deepseek: 0.435, claude: 3, gemini: 1.5, walletLimit: 838.4 },
  { time: "13:00", gpt55: 5, gpt: 0.75, deepseek: 0.435, claude: 3, gemini: 1.5, walletLimit: 836.8 },
  { time: "14:00", gpt55: 5, gpt: 0.75, deepseek: 0.435, claude: 3, gemini: 1.5, walletLimit: 835.9 },
  { time: "15:00", gpt55: 5, gpt: 0.75, deepseek: 0.435, claude: 3, gemini: 1.5, walletLimit: 835.1 },
];

export const agentRules: AgentRule[] = [
  { label: "单笔采购上限", value: "$5.00", tone: "success" },
  { label: "每日总预算", value: "$24.00", tone: "neutral" },
  { label: "自动触发价", value: "<= $0.435 / 1M", tone: "warning" },
  { label: "付款授权", value: "已授权", tone: "success" },
];

export const alerts: AlertItem[] = [
  {
    title: "采购超过单笔限额",
    detail: "GPT-5.5 的采购金额高于当前单笔上限，需要管理员处理。",
    severity: "critical",
    time: "15:08",
  },
  {
    title: "重复采购频率偏高",
    detail: "DeepSeek V4 Pro 在 10 分钟内触发 3 次采购规则。",
    severity: "warning",
    time: "14:52",
  },
  {
    title: "钱包额度低于提醒线",
    detail: "当前可用额度低于今日预算的 30%。",
    severity: "info",
    time: "13:37",
  },
];

export const transactions: Transaction[] = [
  {
    id: "tx-1402",
    time: "15:02",
    asset: "DeepSeek V4 Pro",
    amount: "0.57M input tokens",
    cost: "$0.25",
    status: "Success",
    hash: "0x91a4...e12b",
  },
  {
    id: "tx-1398",
    time: "14:44",
    asset: "GPT-5.4 mini",
    amount: "0.83M input tokens",
    cost: "$0.62",
    status: "Pending",
    hash: "0x48cf...77a9",
  },
  {
    id: "tx-1391",
    time: "13:19",
    asset: "Gemini 3.5 Flash",
    amount: "2.80M input tokens",
    cost: "$0.84",
    status: "Blocked",
    hash: "policy-limit",
  },
];
